make backwards compatible for <4.83
Error: 6 errors occurred:
	* 'org_settings.secrets' is required
	* name is required for each label
	* a SQL query or host vitals criteria is required for each non-manual label
	* 'agent_options' is required
	* 'reports' key is required
	* 'policies' key is required